# Array Tasks:

- Create a 1D NumPy array with values from 10 to 50
- Create a 2D NumPy array of shape (3, 3) with values 1–9
- Find the shape and size of both arrays
- Access the middle element of the 2D array
- Slice the last 2 elements from the 1D array


In [2]:
import numpy as np

In [49]:
arr_1d = np.arange(10, 51)
print("1d array:\n",arr_1d)
print("\nSize:",arr_1d.size)
print("\n Last two elements of array are:",arr_1d[-2:])

1d array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

Size: 41

 Last two elements of array are: [49 50]


In [39]:
arr_2d = np.arange(1, 10).reshape(3,3)
print("2d array:\n", arr_2d)
print("\nSize:",arr_2d.size)
print("Middle  element of a 2D-array:" , arr_2d[1,1])

2d array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Size: 9
Middle  element of a 2D-array: 5


# Maths Tasks:
- Find the mean, median, and standard deviation of the 1D array
- Add 10 to every element of the 1D array
- Multiply every element by 2
- Use np.linspace(0, 1, 5) — explain what it returns
- Generate a random 3×3 matrix of integers between 1 and 100


In [57]:
arr_1d = np.arange(10, 51)
print("1d array:\n",arr_1d)
mean_val = np.mean(arr_1d)
print("\n Mean value:",mean_val)
median_val = np.median(arr_1d)
print("\n Median value:",mean_val)
std_val = np.std(arr_1d)
print("\n Standard deviation:",std_val)
arr_plus_10 = arr_1d + 10
print("\n Array after adding 10 to every element of 1d array:\n", arr_plus_10)
arr_mul_2 = arr_1d * 2
print("\n Array after multiply 2 to every element of 1d array:\n", arr_mul_2)





1d array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

 Mean value: 30.0

 Median value: 30.0

 Standard deviation: 11.832159566199232

 Array after adding 10 to every element of 1d array:
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]

 Array after multiply 2 to every element of 1d array:
 [ 20  22  24  26  28  30  32  34  36  38  40  42  44  46  48  50  52  54
  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86  88  90
  92  94  96  98 100]

 Linespace array: [0.   0.25 0.5  0.75 1.  ]


- The np.linspace(start, stop, num) function returns num evenly spaced values between start and stop, inclusive.

In [58]:
arr_linespace = np.linspace(0,1,5)
print("\n Linespace array:",arr_linespace)


 Linespace array: [0.   0.25 0.5  0.75 1.  ]


In [59]:
array = np.random.randint(3,3)
print("\n Random Matrix:",array)


 Random Matrix: [[0.90648774 0.72406147 0.4904603 ]
 [0.02213141 0.14329512 0.94077412]
 [0.95270203 0.25631372 0.43207427]]
