## Numpy Array Operations:

In [1]:
import numpy as np

### Indexing and Slicing:

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("With Step: ", arr[1:8:2])
print("Negative Indexing: ", arr[-3])

Basic Slicing:  [3 4 5 6 7]
With Step:  [2 4 6 8]
Negative Indexing:  8


In [12]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element of a row " , arr_2d[1,2])
print("Entire Row : ", arr_2d[1])
print("Entire column: ", arr_2d[:,1])


Specific element of a row  6
Entire Row :  [4 5 6]
Entire column:  [2 5 8]


## Sorting

In [17]:
unsorted = np.array([3,5,7,2,4,1,6,9,8])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column" , np.sort(arr_2d_unsorted,axis=0))

Sorted Array:  [1 2 3 4 5 6 7 8 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


## Filtering:

In [19]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers:", even_number)

Even numbers: [ 2  4  6  8 10]


## Filter with mask

In [24]:
mask = numbers > 5
print(mask)
print("Numbers greater than 5 ",numbers[mask])

[False False False False False  True  True  True  True  True]
Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [23]:
indices =[0,2,4]
print(numbers[indices]) 

where_result = np.where(numbers > 5)
print(where_result)
print("NP where ",numbers[where_result])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [34]:
condition_array = np.where(numbers > 5,"true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Merging,Adding and Removing Data:

In [37]:
arr1 = np.array([1,2,3])
arr2 =np.array([4,5,6])

combined =np.concatenate((arr1,arr2)) #as tuple
print("combined arrays:",combined)



combined arrays: [1 2 3 4 5 6]


### Array compatibility:

In [43]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatibility Shapes", a.shape == b.shape)

compatibility Shapes True


In [48]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

# Vstack(vertical):adds new row to the 2d array
with_new_row = np.vstack((original, new_row))
print("original:\n",original)
print("With new row added:\n",with_new_row)

# Hstack(horizontal):adds new column to the 2d array
new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("Original:\n",original)
print("With new column added:\n",with_new_col)
                         

original:
 [[1 2]
 [3 4]]
With new row added:
 [[1 2]
 [3 4]
 [5 6]]
Original:
 [[1 2]
 [3 4]]
With new column added:
 [[1 2 7]
 [3 4 8]]


In [51]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("Array after Deletion:\n",deleted)

Array after Deletion:
 [1 2 4 5]
