## Numpy array and basics
learn about numpy with chai aur code

In [1]:
import numpy as np

### creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:", arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [7]:
py_list = [1,2,3]# double the list print
print("Python list multiplication",py_list * 2)

np_array=np.array([1,2,3]) #element wise multiplication
print("Python array multiplication", np_array * 2)

import time
start = time.time()
py_list =[i*2 for i in range(1000000)]
print("\n List operation time:", time.time() - start)

start = time.time()
py_list =np.arange(1000000) * 2
print("\n Numpy operation time:", time.time() - start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 List operation time: 0.07419300079345703

 Numpy operation time: 0.01679825782775879


### Creating array from scratch

In [13]:
zeros = np.zeros((3,4))
print("Zeros array: \n",zeros)

ones = np.ones((2,3))
print("One array: \n",ones)

full = np.full((2,2),7)
print("Full array: \n",full)

random = np.random.random((2,3))
print("Random array: \n",random)

sequence = np.arange(0,10,2)
print("Sequence array: \n",sequence)


Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.61416638 0.2537235  0.77145154]
 [0.23968123 0.03563869 0.68866532]]
Sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [15]:
vector = np.array([1,2,3])
print("Vector:\n ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrices:\n ", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor:\n ", tensor)

Vector:
  [1 2 3]
Matrices:
  [[1 2 3]
 [4 5 6]]
Tensor:
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties

In [17]:
arr = np.array ([[1,2,3],
                 [4,5,6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size",arr.size)
print("Data type ",arr.dtype) 

Shape  (2, 3)
Dimension  2
Size 6
Data type  int64


### Array reshape

In [25]:
arr = np.arange(12)
print("Original array:\n ", arr)

reshaped = arr.reshape(3,4)
print("\n Reshaped array:\n", reshaped)

flattend = reshaped.flatten()
print("\n Flattened array: \n",flattend)

# ravel (return view,instead of copy)
raveled = reshaped.ravel()
print("\n Raveled array: \n",raveled)

#Transpose 
transpose = reshaped.T
print("\n Transposed array: \n",transpose)


Original array:
  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
